<!-- Instagram Banner Section Start -->
<div class="instagram-banner fix section-padding">
        <div class="instagram-wrapper">
            <h3 class="text-center wow fadeInUp" data-wow-delay=".3s">Follow Instagram</h3>
            <div class="swiper instagram-banner-slider">
                <div class="swiper-wrapper">
                    <div class="swiper-slide">
                        <div class="instagram-banner-items">
                            <div class="banner-image">
                                <img src="assets/img/instagram/01.jpg" alt="insta-img">
                                <a href="index.html" class="icon">
                                        <i class="fa-brands fa-instagram"></i>
                                    </a>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="instagram-banner-items">
                            <div class="banner-image">
                                <img src="assets/img/instagram/02.jpg" alt="insta-img">
                                <a href="index.html" class="icon">
                                        <i class="fa-brands fa-instagram"></i>
                                    </a>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="instagram-banner-items">
                            <div class="banner-image">
                                <img src="assets/img/instagram/03.jpg" alt="insta-img">
                                <a href="index.html" class="icon">
                                        <i class="fa-brands fa-instagram"></i>
                                    </a>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="instagram-banner-items">
                            <div class="banner-image">
                                <img src="assets/img/instagram/04.jpg" alt="insta-img">
                                <a href="index.html" class="icon">
                                        <i class="fa-brands fa-instagram"></i>
                                    </a>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="instagram-banner-items">
                            <div class="banner-image">
                                <img src="assets/img/instagram/05.jpg" alt="insta-img">
                                <a href="index.html" class="icon">
                                        <i class="fa-brands fa-instagram"></i>
                                    </a>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide">
                        <div class="instagram-banner-items">
                            <div class="banner-image">
                                <img src="assets/img/instagram/06.jpg" alt="insta-img">
                                <a href="index.html" class="icon">
                                        <i class="fa-brands fa-instagram"></i>
                                    </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>